### ISSUE TITLE
input|vslider css bugged

### ISSUE THREAD

**Issue by 8ctopus** [c-smile/sciter-js-sdk#109]
**Describe the bug**

vslider is bugged as shown in the video because of incorrect css skinning

https://user-images.githubusercontent.com/13252042/118619964-7ea07600-b7de-11eb-8bbb-78ad287c2b82.mp4

Microsoft Windows 10 Pro
10.0.19042 Build 19042
scapp.exe 4.4.7.4

**To Reproduce**
```html
<html
    window-resizable="true"
    window-width="340dip"
    window-height="230dip"
>
<head>
<title>sciter vslider bug</title>
</head>
<body>
    <input|vslider min=0 max=100 value=50 buddy="p2a-buddy" /><b id="p2a-buddy">x</b>
</body>
</html>
```

To fix it, update ux-master.css with the following std-vslider ruleset

```css
@set std-vslider < std-vslider-base
{
  :root
  {
    display:inline-block;
    padding:12dip;
    width:3dip;
    height:100dip;
    background: color(accent);
    background-clip: content-box;
    background-image: url(stock:block);
    background-size: 100% length(slider-position) 11dip;
    fill: color(button-face);
    stroke-width:0;
  }

  :root > .slider
  {
    @STD-BUTTON-NORMAL;
    size:11dip;
    background:color(button-face);
    border-radius:7dip;
    border-color: color(accent);
  }

  :root > .slider:hover    { @STD-BUTTON-HOVER; }
  :root > .slider:active   { @STD-BUTTON-PRESSED; }
  :root:disabled > { fill: color(widget-border); }
  :root:disabled > .slider { background: color(widget-back); border-color: color(widget-border); }
  :root:tab-focus { @STD-BUTTON-TAB-FOCUS; border-radius: length(border-radius); }
}
```
