### ISSUE TITLE
3 CSS Bugs

### ISSUE THREAD

**Issue by GirkovArpa** [c-smile/sciter-js-sdk#182]
**Describe the bug**
- Negative percentages in CSS `foreground` property are clamped to zero.
- `foreground` transition is desynchronized with `transform` transition.
- Foreground doesn't respect border-radius (that's why I'm using `background` in the code below)

**To Reproduce**
1. Hover the button
2. Observe the bar growing wider as it moves across the button 
3. Leave the button before `5000ms` (before the `transform: translate` transition completes)
4. Observe the `foreground` transition reverse MUCH faster than the `transform: translate` does (they should complete at the same time).

**Expected behavior**
I want the diagonal white bar to slide back and forth across the button on mouseenter and mouseleave.

**Screenshots**
- Expected:
https://codepen.io/crayon-code/pen/abmgooe
- Observed:
![screenshot](https://i.imgur.com/w6oYQHV.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
The second bug, where `foreground` transition operates at a different speed than the `transform: translate` transition, occurs when `mouseenter` or `mouseleave` occurs before the previous transition is completed. 

```html
<!DOCTYPE html>
<html window-frame="none" window-blurbehind="ultra-light">

  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <link href="main.css" rel="stylesheet">
  </head>

  <body>
    <div #container .col>
      <div .glass-button>Click me!</div>
    </div>
  </body>

</html>
```

```css
html, body {
  height: 100%;
  margin: 0;
  background-color: transparent;
  box-sizing: border-box;
}

#container {
  background: linear-gradient(322deg, #ba4affBf, rgba(186, 74, 255, 0) 70%);
  vertical-align: middle;
  height: *;
}

#container::before {
  z-index: -1;
  position: absolute;
  width: 100%;
  height: 100%;
  background: linear-gradient(24deg, #00ffc6Bf, rgba(0, 255, 198, 0) 35%);
  foreground: linear-gradient(178deg, #008affBf, rgba(0, 138, 255, 0) 70%);
}

#container::before:hover {
  background-position: 50% 50%;
}

.col {
  flow: vertical;
}

.row {
  flow: horizontal;
}

.glass-button {
  position: relative;
  font-size: 35px;
  color: white;
  font-weight: bold;
  margin: auto;
  border: 1px solid white;
  border-radius: 0.5rem;
  padding: 1em;
  width: max-content;
  border: 1px solid rgba(255, 255, 255, 0.6);
  background-color: rgba(255, 255, 255, 0.1);
  transition: transform 1000ms ease-out, background 1000ms ease-out;
  transform: translate(0, 0);
  cursor: pointer;
  box-shadow: 0px 2rem 3rem rgba(0, 0, 0, 0.1);
  background: linear-gradient(-45deg, transparent -75%, transparent -35%, rgba(255, 255, 255, 0.2) -35%, rgba(255, 255, 255, 0.2) -30%, rgba(255, 255, 255, 0.4) -30%, rgba(255, 255, 255, 0.4) -15%, rgba(255, 255, 255, 0.2) -15%, rgba(255, 255, 255, 0.2) -10%, transparent -75%);
}

.glass-button:hover {
  transform: translate(0, -25%);
  background: linear-gradient(-45deg, transparent 75%, transparent 115%, rgba(255, 255, 255, 0.2) 115%, rgba(255, 255, 255, 0.2) 120%, rgba(255, 255, 255, 0.4) 120%, rgba(255, 255, 255, 0.4) 135%, rgba(255, 255, 255, 0.2) 135%, rgba(255, 255, 255, 0.2) 140%, transparent 75%);
}
```
